### ISSUE TITLE
Виправ в  медіа запиті розміри блоків ,а  то ви ходить така штука

### ISSUE THREAD

**Issue by Ultimo2905** [itsergeysobolit/Landing-fitness#14]
![image](https://user-images.githubusercontent.com/43437388/48251007-e7862680-e408-11e8-9068-91b60011eeae.png)
![image](https://user-images.githubusercontent.com/43437388/48251104-3633c080-e409-11e8-9b41-7b62efd3b0c3.png)

**Comment by itsergeysobolit** [comment]
Там ссылка сделана через absolute, it's OK.
