### ISSUE TITLE
Optional: Для мобільної версії можна меню зробити (спливаюче меню)

### ISSUE THREAD

**Issue by Ultimo2905** [itsergeysobolit/Landing-fitness#19]
![image](https://user-images.githubusercontent.com/43437388/48252103-77799f80-e40c-11e8-91d8-448aaaaf56ab.png)
Можно зробити по типу такого, якщо захочеш
![image](https://user-images.githubusercontent.com/43437388/48252136-91b37d80-e40c-11e8-91d6-4ac30a095e5c.png)

**Comment by itsergeysobolit** [comment]
Дякую за пропозицію :)
