### ISSUE TITLE
Form should be pulled to right

### ISSUE THREAD

**Issue by rudnitskih** [itsergeysobolit/Landing-fitness#23]
<img width="1238" alt="screen shot 2018-11-17 at 10 32 28" src="https://user-images.githubusercontent.com/8848858/48659044-3ad52600-ea54-11e8-8f18-62b9ee0042f2.png">

**Comment by itsergeysobolit** [comment]
Проверь ещё раз, потому что там у меня свойство justify-content:  flex-end;
